build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
image: "gluetun-{arch}"
args:
  GLUETUN_VERSION: "v3.40.0"
labels:
  io.hass.type: addon
  io.hass.version: "1.0.0"
  io.hass.name: "Gluetun VPN qbittorrent"
  io.hass.description: "VPN client for multiple providers with proxy services & qbittorrent" 
