name: "Gluetun-qbittorent"
version: "1.0.0"
slug: "Gluetun-qbittorent"
description: "VPN client for multiple providers with proxy services"
url: "https://github.com/nyok92/hassio-addons/tree/main/Gluetun-qbittorent"
image: "ghcr.io/nyok92/{arch}-Gluetun-qbittorent"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
ports:
  8888/tcp: 8888
  8388/tcp: 8388
  8388/udp: 8388
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - share:rw
webui: "http://[HOST]:[PORT:8888]"
ingress: true
ingress_port: 8888
panel_icon: mdi:vpn
homeassistant_api: true
hassio_api: true
hassio_role: manager 
