# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Traefik
version: "3.3.5"
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy.
url: "https://github.com/nyok92/hassio-addons/tree/main/traefik"
image: "ghcr.io/nyok92/{arch}-traefik"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
init: false
ports:
  80/tcp: 80
  443/tcp: 443
  443/udp: 443
  8080/tcp: null
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  443/udp: HTTPS3
  8080/tcp: Dashboard
webui: http://[HOST]:[PORT:8080]/dashboard/
ingress: true
ingress_port: 8080
ingress_entry: dashboard/
panel_title: Traefik
panel_icon: mdi:earth-arrow-right
map:
  - addon_config:rw
#  - share:rw
  - ssl:rw
options:
  timezone: "Europe/Paris"
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  dynamic_configuration_path: "/config/traefik/"
  letsencrypt:
    enabled: false
    email: yourmail@test.com
    challenge_type: tlsChallenge
  env_vars: []
schema:
  timezone: "str"
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  env_vars:
    - str
