# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Borg back up addon"
  org.opencontainers.image.description: "Boorg backup add-on"
  org.opencontainers.image.source: "https://github.com/nyok92/hassio-addons/borgbackup"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  CLI_VERSION: "4.31.0"
