ARG BUILD_FROM=ghcr.io/nyok92/frigate:latest
FROM $BUILD_FROM

ARG BUILD_ARCH

LABEL org.opencontainers.image.title="Frigate" \
      org.opencontainers.image.description="Frigate app rk3588 mainline" \
      org.opencontainers.image.source="https://github.com/nyok92/hassio-addons/frigate" \
      org.opencontainers.image.licenses="Apache-2.0"
