#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# permissions
#lsiown -R abc:abc \
#    /config


# Overhauling userbase
#
echo "root:x:0:root" > /etc/group
echo "root:x:0:0:root:/root:/bin/ash" > /etc/passwd
if [ "$GRP_ID" -ne 0 ]; then
    addgroup -g "$GRP_ID" -S abc;
fi
if [ "$USR_ID" -ne 0 ]; then
    adduser -u "$USR_ID" -S abc -G abc;
fi
 
# Configuring folders and permissions   
# 
chown -R "$USR_ID":"$GRP_ID"   /config
